name: deno deploy ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ['1.34.0']

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - run: deno --version

      - name: Format
        run: deno fmt --check

      - name: Build Deno Module
        run: deno run --reload mod.ts

      - name: Run tests
        run: deno task start